# MongoDB Atlas (depuis le repo GitHub d'origine)
spring.data.mongodb.uri=mongodb+srv://greendesk_user:greendesk_pass@greendesk.yyw2ky1.mongodb.net/greendesk_db?retryWrites=true&w=majority
spring.data.mongodb.database=greendesk_db

# MongoDB Docker (commenté)
# spring.data.mongodb.uri=mongodb://admin:adminpass@mongodb:27017/greendesk?authSource=admin
# spring.data.mongodb.database=greendesk

# Spring Boot
spring.jackson.serialization.indent_output=true
spring.jackson.time-zone=Europe/Paris
server.port=8080

# ==================== NOTIFICATIONS ====================
# Activer l'affichage des notifications dans la console
notifications.console.enabled=true

# Configuration email (optionnel)
notifications.email.enabled=false
notifications.email.to=admin@greendesk.local

# Configuration SMTP (à décommenter si on utilise l'email)
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=votre.email@gmail.com
# spring.mail.password=votre-mot-de-passe
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# ==================== TOMORROW.IO (Feature 1 + Feature 2) ====================
# Clé API : https://www.tomorrow.io/
tomorrow.api.key=${TOMORROW_API_KEY:}
tomorrow.webhook.url=${TOMORROW_WEBHOOK_URL:http://localhost:8080/api/weather/webhook}

#Agenda Google Calendar pour la prod
google.calendar.id=c_b7d9047f65b544d190cb138ed8882a183f1f33fa07ad8ca18fc3cd616735a040@group.calendar.google.com
google.api.credentials-path=src/main/resources/google/service-account.json