# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://greendesk_user:greendesk_pass@greendesk.yyw2ky1.mongodb.net/greendesk_db?retryWrites=true&w=majority
spring.data.mongodb.database=greendesk_db

# Spring Boot
spring.jackson.serialization.indent_output=true
server.port=8080